name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2.20.0
        with:
          channel: stable
          flutter-version: 3.27.4
      - run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter test
